image: Visual Studio 2017

version: 1.0.{build}

environment:
  # Don't report back to the mothership
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOCKER_USER: corts
  DOCKER_PASS:
    secure: ATrglohIlg/NHRCeHMytmg==

init:
- ps: >-
    $Env:LABEL = "CI" + $Env:APPVEYOR_BUILD_NUMBER.PadLeft(5, "0");
    $ENV:IMAGENAME = 'cortside/chiron-base'

install:
  - ps: docker login -u="$env:DOCKER_USER" -p="$env:DOCKER_PASS"
  - docker version

build_script:
- ps: ./build.ps1
