image: Visual Studio 2017

version: 1.0.{build}

configuration:
- Debug

platform: Any CPU

environment:
  # Don't report back to the mothership
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOCKER_USER: victors2
  DOCKER_PASS:
    secure: kgpRGG5woa2ZoXDFtIF+8w==  

#HINT:  thanks jeff ;)    

init:
- ps: >-
    $Env:LABEL = "CI" + $Env:APPVEYOR_BUILD_NUMBER.PadLeft(5, "0");
    $ENV:IMAGENAME = 'spring2/c7-auth'

install:
  - ps: docker login -u="$env:DOCKER_USER" -p="$env:DOCKER_PASS"
  - docker version

before_build:
- set DNX_BUILD_VERSION=%APPVEYOR_BUILD_NUMBER%x
- dotnet --info
- ps: ('{{"build":{{"version":"{0}","timestamp":"{1}"}}}}' -f $env:APPVEYOR_BUILD_VERSION, (get-date -f G)) | out-file build.json -Encoding ascii


build:
  verbosity: minimal

build_script: 
- npm install -g bower
- npm install -g node-sass
- cd src/c7.auth/ & bower install
- node-sass --output-style expanded src/c7.auth/wwwroot/styles/site.scss src/c7.auth/wwwroot/styles/site.css
- node-sass --output-style compressed src/c7.auth/wwwroot/styles/site.scss src/c7.auth/wwwroot/styles/site.min.css
- ps: ./appveyor-build.ps1 $ENV:APPVEYOR_REPO_BRANCH $ENV:APPVEYOR_BUILD_VERSION $ENV:IMAGENAME


after_build:
- dotnet pack "src\C7.Auth" --no-build -o ..\..\artifacts

test_script:
- ps: ./appveyor-test.ps1 $ENV:APPVEYOR_REPO_BRANCH $ENV:APPVEYOR_BUILD_VERSION $ENV:IMAGENAME

artifacts:
- path: artifacts\**\*.*

cache:
- '%USERPROFILE%\.nuget\packages'
  
nuget:
  account_feed: true