image: Visual Studio 2017

version: 1.0.{build}

configuration:
- Debug

platform: Any CPU

environment:
  # Don't report back to the mothership
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOCKER_USER: victors2
  DOCKER_PASS:
    secure: kgpRGG5woa2ZoXDFtIF+8w==  

#HINT:  thanks jeff ;)    

init:
- ps: >-
    $Env:LABEL = "CI" + $Env:APPVEYOR_BUILD_NUMBER.PadLeft(5, "0");
    $ENV:IMAGENAME = 'spring2/chiron-customerregistrationapi'

install:
  - ps: docker login -u="$env:DOCKER_USER" -p="$env:DOCKER_PASS"
  - docker version

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

before_build:
- set DNX_BUILD_VERSION=%APPVEYOR_BUILD_NUMBER%
- dotnet --info
- ps: ('{{"build":{{"version":"{0}","timestamp":"{1}"}}}}' -f $env:APPVEYOR_BUILD_VERSION, (get-date -f G)) | out-file build.json -Encoding ascii

build:
  verbosity: minimal

build_script:
- ps: ./appveyor-build.ps1 $ENV:APPVEYOR_REPO_BRANCH $ENV:APPVEYOR_BUILD_VERSION $ENV:IMAGENAME


after_build:
- dotnet pack "src\Chiron.Registration.Customer.WebApi" --no-build -o artifacts

test_script:
- ps: ./appveyor-test.ps1 $ENV:APPVEYOR_REPO_BRANCH $ENV:APPVEYOR_BUILD_VERSION $ENV:IMAGENAME

artifacts:
- path: artifacts\**\*.*

cache:
- '%USERPROFILE%\.nuget\packages'
  
nuget:
  account_feed: true